# Static Web Scraping 1.0

In [55]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

| Parser | Speed | Built-in | Best Use |
|---|---|---|---|
| html.parser | Medium | Yes | Beginners/general |
| lxml | Fast | No | Real scraping projects |
| html5lib | Slow | No | Broken HTML |
| xml | Fast | Depends | XML data |

### Page 1: Hockey Teams: Forms, Searching and Pagination
```
https://www.scrapethissite.com/pages/forms/

In [4]:
url = r"https://www.scrapethissite.com/pages/forms/"
response = requests.get(url)

In [5]:
soup = BeautifulSoup(response.text, "html")

# print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping
  </title>
  <link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <meta content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components." name="description"/>
  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
  <link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
  <meta content="noindex" name="robots"/>
 </head>
 <body>
  <nav id="site-nav">
   <div class="container">
    <div class="col-md-12">
     <ul class="nav nav-tabs">
      <li id="nav-homepage">
       <a class="nav-link hidden-sm hidden-xs" href="/">
        <img id="nav-logo" src="/static/images/scraper-icon.png"/>
        Scrape This Site
       </a>
      </li>
      <li id="nav-sandbox">
       <a class="nav-link" href="/pages/">
        <i class="glyphicon glyphicon-console hidden-sm hidden-xs">
        </i>
        Sandbox
       </a>
      </li>
      <li id="nav-lessons">
       <a class="nav-link" href="/lessons/">
        <i class="glyphicon glyphicon-education hidden-sm hidden-xs">
        </i>
        Lessons
       </a>
      </li>
      <li id="nav-faq">
       <a class="nav-link" href="/faq/">
        <i class="glyphicon glyphicon-flag hidden-sm hidden-xs">
        </i>
        FAQ
       </a>
      </li>
      <li class="pull-right" id="nav-login">
       <a class="nav-link" href="/login/">
        Login
       </a>
      </li>
     </ul>
    </div>
   </div>
  </nav>
  <script type="text/javascript">
   var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
  </script>
  <div id="page">
   <section id="hockey">
    <div class="container">
     <div class="row">
      <div class="col-md-12">
       <h1>
        Hockey Teams: Forms, Searching and Pagination
        <small>
         25 items
        </small>
       </h1>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       <p class="lead">
        Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
       </p>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-6">
       <p>
        <i class="glyphicon glyphicon-education">
        </i>
        There are
        <a href="/lessons/">
         8 video lessons
        </a>
        that show you how to scrape this page.
       </p>
       <hr/>
      </div>
      <div class="col-md-6 text-right">
       <p>
        Data via
        <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">
         http://www.opensourcesports.com/hockey/
        </a>
       </p>
       <hr/>
      </div>
     </div>
     <div class="row search-area">
      <div class="col-md-12 text-center">
       <form action="/pages/forms/" class="form form-inline" method="GET">
        <label for="q">
         Search for Teams:
        </label>
        <input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
        <input class="btn btn-primary" type="submit" value="Search"/>
       </form>
       <hr/>
      </div>
     </div>
     <!--.row.search-area-->
     <table class="table">
      <tr>
       <th>
        Team Name
       </th>
       <th>
        Year
       </th>
       <th>
        Wins
       </th>
       <th>
        Losses
       </th>
       <th>
        OT Losses
       </th>
       <th>
        Win %
       </th>
       <th>
        Goals For (GF)
       </th>
       <th>
        Goals Against (GA)
       </th>
       <th>
        + / -
       </th>
      </tr>
      <tr class="team">
       <td class="name">
        Boston Bruins
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        44
       </td>
       <td class="losses">
        24
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.55
       </td>
       <td class="gf">
        299
       </td>
       <td class="ga">
        264
       </td>
       <td class="diff text-success">
        35
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Buffalo Sabres
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        30
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        292
       </td>
       <td class="ga">
        278
       </td>
       <td class="diff text-success">
        14
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Calgary Flames
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        46
       </td>
       <td class="losses">
        26
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.575
       </td>
       <td class="gf">
        344
       </td>
       <td class="ga">
        263
       </td>
       <td class="diff text-success">
        81
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Chicago Blackhawks
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        49
       </td>
       <td class="losses">
        23
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.613
       </td>
       <td class="gf">
        284
       </td>
       <td class="ga">
        211
       </td>
       <td class="diff text-success">
        73
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Detroit Red Wings
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        34
       </td>
       <td class="losses">
        38
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.425
       </td>
       <td class="gf">
        273
       </td>
       <td class="ga">
        298
       </td>
       <td class="diff text-danger">
        -25
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Edmonton Oilers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        37
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.463
       </td>
       <td class="gf">
        272
       </td>
       <td class="ga">
        272
       </td>
       <td class="diff text-success">
        0
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Hartford Whalers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        38
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        238
       </td>
       <td class="ga">
        276
       </td>
       <td class="diff text-danger">
        -38
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Los Angeles Kings
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        46
       </td>
       <td class="losses">
        24
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.575
       </td>
       <td class="gf">
        340
       </td>
       <td class="ga">
        254
       </td>
       <td class="diff text-success">
        86
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Minnesota North Stars
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        27
       </td>
       <td class="losses">
        39
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.338
       </td>
       <td class="gf">
        256
       </td>
       <td class="ga">
        266
       </td>
       <td class="diff text-danger">
        -10
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Montreal Canadiens
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        39
       </td>
       <td class="losses">
        30
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.487
       </td>
       <td class="gf">
        273
       </td>
       <td class="ga">
        249
       </td>
       <td class="diff text-success">
        24
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New Jersey Devils
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        32
       </td>
       <td class="losses">
        33
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.4
       </td>
       <td class="gf">
        272
       </td>
       <td class="ga">
        264
       </td>
       <td class="diff text-success">
        8
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New York Islanders
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        25
       </td>
       <td class="losses">
        45
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.312
       </td>
       <td class="gf">
        223
       </td>
       <td class="ga">
        290
       </td>
       <td class="diff text-danger">
        -67
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New York Rangers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        31
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.45
       </td>
       <td class="gf">
        297
       </td>
       <td class="ga">
        265
       </td>
       <td class="diff text-success">
        32
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Philadelphia Flyers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        33
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.412
       </td>
       <td class="gf">
        252
       </td>
       <td class="ga">
        267
       </td>
       <td class="diff text-danger">
        -15
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Pittsburgh Penguins
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        41
       </td>
       <td class="losses">
        33
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.512
       </td>
       <td class="gf">
        342
       </td>
       <td class="ga">
        305
       </td>
       <td class="diff text-success">
        37
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Quebec Nordiques
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        16
       </td>
       <td class="losses">
        50
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.2
       </td>
       <td class="gf">
        236
       </td>
       <td class="ga">
        354
       </td>
       <td class="diff text-danger">
        -118
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        St. Louis Blues
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        47
       </td>
       <td class="losses">
        22
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.588
       </td>
       <td class="gf">
        310
       </td>
       <td class="ga">
        250
       </td>
       <td class="diff text-success">
        60
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Toronto Maple Leafs
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        23
       </td>
       <td class="losses">
        46
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.287
       </td>
       <td class="gf">
        241
       </td>
       <td class="ga">
        318
       </td>
       <td class="diff text-danger">
        -77
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Vancouver Canucks
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        28
       </td>
       <td class="losses">
        43
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.35
       </td>
       <td class="gf">
        243
       </td>
       <td class="ga">
        315
       </td>
       <td class="diff text-danger">
        -72
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Washington Capitals
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        37
       </td>
       <td class="losses">
        36
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.463
       </td>
       <td class="gf">
        258
       </td>
       <td class="ga">
        258
       </td>
       <td class="diff text-success">
        0
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Winnipeg Jets
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        26
       </td>
       <td class="losses">
        43
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.325
       </td>
       <td class="gf">
        260
       </td>
       <td class="ga">
        288
       </td>
       <td class="diff text-danger">
        -28
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Boston Bruins
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        32
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.45
       </td>
       <td class="gf">
        270
       </td>
       <td class="ga">
        275
       </td>
       <td class="diff text-danger">
        -5
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Buffalo Sabres
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        289
       </td>
       <td class="ga">
        299
       </td>
       <td class="diff text-danger">
        -10
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Calgary Flames
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        296
       </td>
       <td class="ga">
        305
       </td>
       <td class="diff text-danger">
        -9
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Chicago Blackhawks
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        29
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.45
       </td>
       <td class="gf">
        257
       </td>
       <td class="ga">
        236
       </td>
       <td class="diff text-success">
        21
       </td>
      </tr>
     </table>
     <div class="row pagination-area">
      <div class="col-md-10 text-center">
       <ul class="pagination">
        <li>
         <a href="/pages/forms/?page_num=1">
          1
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=2">
          2
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=3">
          3
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=4">
          4
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=5">
          5
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=6">
          6
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=7">
          7
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=8">
          8
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=9">
          9
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=10">
          10
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=11">
          11
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=12">
          12
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=13">
          13
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=14">
          14
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=15">
          15
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=16">
          16
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=17">
          17
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=18">
          18
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=19">
          19
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=20">
          20
         </a>

#### find() vs find_all()


- class="" → use class_
- id="" → use id
- for single attribute -> use href=""
- for custom attribute -> use attrs={"data-id": "12"})

```
soup.find(
    "a",
    attrs={
        "class": "btn",
        "href": "/login"
    }
)

```
```parent = soup.find(...) ```

```children = parent.find_all(...)```

In [34]:
nav = soup.find("nav", id="site-nav").find("a", href="/")
print(nav.text.strip())

Scrape This Site

In [32]:
nav_tabs = soup.find("ul", class_="nav-tabs").find_all("a")
texts = [link.text.strip() for link in nav_tabs[1:]]
print(texts)

['Sandbox', 'Lessons', 'FAQ', 'Login']

#### select_one() vs select()
``` Elements + Attributes + Tree Structure ```

soup.select_one("nav#site-nav div.container ul")
  ```
  nav with id=site-nav
    -> div with class=container
        -> ul
```
soup.select("li.item")
``` 
    Returns all matching elements.

In [33]:
nav = soup.select_one('nav#site-nav a[href="/"]')

print(nav.text.strip())

Scrape This Site

In [35]:
nav_tabs = soup.select("ul.nav-tabs a")
texts = [link.text.strip() for link in nav_tabs[1:]]

print(texts)

['Sandbox', 'Lessons', 'FAQ', 'Login']

### Page 2: List of the largest public / publicly traded companies
```
https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue

In [56]:
url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'
headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

In [57]:
soup = BeautifulSoup(response.text, "html.parser")

print(soup.prettify())

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard" dir="ltr" lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   List of largest companies in the United States by revenue - Wikipedia
  </title>
  <script>
   (function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"a39c11f8-982b-4148-b1c8-ccc58bdf053e","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_largest_companies_in_the_United_States_by_revenue","wgTitle":"List of largest companies in the United States by revenue","wgCurRevisionId":1354288064,"wgRevisionId":1354288064,"wgArticleId":61181662,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Use mdy dates from April 2025","Economy of the United States-related lists","Lists of companies by revenue","Lists of largest private companies by country","Lists of companies of the United States"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_largest_companies_in_the_United_States_by_revenue","wgRelevantArticleId":61181662,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditForceShowCaptcha":false,"wgConfirmEditHCaptchaVisualEditorOnLoadIntegrationEnabled":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":30000,"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[]},"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgULSLanguageSelectorV2Enabled":false,"wgWikibaseItemId":"Q1860802","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGESuggestedEditsTaskTypes":{"taskTypes":["copyedit","link-recommendation"],"unavailableTaskTypes":[]},"wgGETopicsMatchModeEnabled":false,"wgGELevelingUpEnabledForUser":false,"wgPersonalDashboardMenuVisible":false};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.wikimediamessages.styles":"ready","ext.cite.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.parsermigration.survey","ext.cite.ux-enhancements","site","mediawiki.page.ready","jquery.tablesorter","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.testKitchen","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init","ext.growthExperiments.SuggestedEditSession"];
  </script>
  <script>
   (RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});
  </script>
  <link href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
  <script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022">
  </script>
  <meta content="" name="ResourceLoaderDynamicStyles"/>
  <link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
  <meta content="MediaWiki 1.47.0-wmf.2" name="generator"/>
  <meta content="origin" name="referrer"/>
  <meta content="origin-when-cross-origin" name="referrer"/>
  <meta content="max-image-preview:standard" name="robots"/>
  <meta content="telephone=no" name="format-detection"/>
  <meta content="width=1120" name="viewport"/>
  <meta content="List of largest companies in the United States by revenue - Wikipedia" property="og:title"/>
  <meta content="website" property="og:type"/>
  <link href="//upload.wikimedia.org" rel="preconnect"/>
  <link href="/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
  <link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
  <link href="/static/favicon/wikipedia.ico" rel="icon"/>
  <link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
  <link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
  <link href="https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue" rel="canonical"/>
  <link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
  <link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
  <link href="//meta.wikimedia.org" rel="dns-prefetch">
   <link href="auth.wikimedia.org" rel="dns-prefetch"/>
  </link>
 </head>
 <body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-List_of_largest_companies_in_the_United_States_by_revenue rootpage-List_of_largest_companies_in_the_United_States_by_revenue skin-vector-2022 action-view">
  <div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region">
  </div>
  <a class="mw-jump-link" href="#bodyContent">
   Jump to content
  </a>
  <div class="vector-header-container">
   <header class="vector-header mw-header no-font-mode-scale">
    <div class="vector-header-start">
     <nav aria-label="Site" class="vector-main-menu-landmark">
      <div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
       <input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
       <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label">
        <span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu">
        </span>
        <span class="vector-dropdown-label-text">
         Main menu
        </span>
       </label>
       <div class="vector-dropdown-content">
        <div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
         <div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
          <div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
           <div class="vector-pinnable-header-label">
            Main menu
           </div>
           <button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">
            move to sidebar
           </button>
           <button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">
            hide
           </button>
          </div>
          <div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
           <div class="vector-menu-heading">
            Navigation
           </div>
           <div class="vector-menu-content">
            <ul class="vector-menu-content-list">
             <li class="mw-list-item" id="n-mainpage-description">
              <a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]">
               <span>
                Main page
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-contents">
              <a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia">
               <span>
                Contents
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-currentevents">
              <a href="/wiki/Portal:Current_events" title="Articles related to current events">
               <span>
                Current events
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-randompage">
              <a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]">
               <span>
                Random article
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-aboutsite">
              <a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works">
               <span>
                About Wikipedia
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-contactpage">
              <a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia">
               <span>
                Contact us
               </span>
              </a>
             </li>
            </ul>
           </div>
          </div>
          <div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
           <div class="vector-menu-heading">
            Contribute
           </div>
           <div class="vector-menu-content">
            <ul class="vector-menu-content-list">
             <li class="mw-list-item" id="n-help">
              <a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia">
               <span>
                Help
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-introduction">
              <a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia">
               <span>
                Learn to edit
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-portal">
              <a href="/wiki/Wikipedia:Community_portal" title="The hub for editors">
               <span>
                Community portal
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-recentchanges">
              <a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]">
               <span>
                Recent changes
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-upload">
              <a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia">
               <span>
                Upload file
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-specialpages">
              <a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]">
               <span>
                Special pages
               </span>
              </a>
             </li>
            </ul>
           </div>
          </div>
         </div>
        </div>
       </div>
      </div>
     </nav>
     <a class="mw-logo" href="/wiki/Main_Page">
      <img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
      <span class="mw-logo-container skin-invert">
       <img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
       <img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
      </span>
     </a>
    </div>
    <div class="vector-header-end">
     <div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
      <a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]">
       <span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search">
       </span>
       <span>
        Search
       </span>
      </a>
      <div class="vector-typeahead-search-container">
       <div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
        <form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
         <div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
          <div class="cdx-text-input cdx-text-input--has-start-icon">
           <input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
           <span class="cdx-text-input__icon cdx-text-input__start-icon">
           </span>
          </div>
          <input name="title" type="hidden" value="Special:Search"/>
         </div>
         <button class="cdx-button cdx-search-input__end-button">
          Search
         </button>
        </form>
       </div>
      </div>
     </div>
     <nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
      <div class="vector-user-links-main">
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <nav aria-label="Appearance" class="vector-appearance-landmark">
        <div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
         <input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
         <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label">
          <span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance">
          </span>
          <span class="vector-dropdown-label-text">
           Appearance
          </span>
         </label>
         <div class="vector-dropdown-content">
          <div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
          </div>
         </div>
        </div>
       </nav>
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
          <li class="mw-list-item user-links-collapsible-item" id="pt-sitesupport-2">
           <a class="" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en">
            <span>
             Donate
            </span>
           </a>
          </li>
          <li class="mw-list-item user-links-collapsible-item" id="pt-createaccount-2">
           <a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+companies+in+the+United+States+by+revenue" title="You are encouraged to create an account and log in; however, it is not mandatory">
            <span>
             Create account
            </span>
           </a>
          </li>
          <li class="mw-list-item user-links-collapsible-item" id="pt-login-2">

In [90]:
table = soup.find_all('table')[0]

print(table.prettify())

<table class="wikitable sortable">
 <caption>
 </caption>
 <tbody>
  <tr>
   <th>
    Rank
   </th>
   <th>
    Name
   </th>
   <th>
    Industry
   </th>
   <th>
    Revenue
    <br/>
    (USD millions)
   </th>
   <th>
    Revenue growth
   </th>
   <th>
    Employees
   </th>
   <th>
    Headquarters
   </th>
  </tr>
  <tr>
   <td>
    1
   </td>
   <td>
    <a href="/wiki/Walmart" title="Walmart">
     Walmart
    </a>
   </td>
   <td>
    Retail
   </td>
   <td style="text-align:center;">
    680,985
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    5.1%
   </td>
   <td style="text-align:center;">
    2,100,000
   </td>
   <td>
    <a href="/wiki/Bentonville,_Arkansas" title="Bentonville, Arkansas">
     Bentonville, Arkansas
    </a>
   </td>
  </tr>
  <tr>
   <td>
    2
   </td>
   <td>
    <a href="/wiki/Amazon_(company)" title="Amazon (company)">
     Amazon
    </a>
   </td>
   <td>
    Retail and cloud computing
   </td>
   <td style="text-align:center;">
    637,959
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    11.0%
   </td>
   <td style="text-align:center;">
    1,556,000
   </td>
   <td>
    <a href="/wiki/Seattle" title="Seattle">
     Seattle, Washington
    </a>
   </td>
  </tr>
  <tr>
   <td>
    3
   </td>
   <td>
    <a href="/wiki/UnitedHealth_Group" title="UnitedHealth Group">
     UnitedHealth Group
    </a>
   </td>
   <td>
    Healthcare
   </td>
   <td style="text-align:center;">
    400,278
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    7.7%
   </td>
   <td style="text-align:center;">
    400,000
   </td>
   <td>
    <a href="/wiki/Minnetonka,_Minnesota" title="Minnetonka, Minnesota">
     Minnetonka, Minnesota
    </a>
   </td>
  </tr>
  <tr>
   <td>
    4
   </td>
   <td>
    <a class="mw-redirect" href="/wiki/Apple_Inc" title="Apple Inc">
     Apple
    </a>
   </td>
   <td>
    Technology
   </td>
   <td style="text-align:center;">
    391,035
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    2.0%
   </td>
   <td style="text-align:center;">
    164,000
   </td>
   <td>
    <a href="/wiki/Cupertino,_California" title="Cupertino, California">
     Cupertino, California
    </a>
   </td>
  </tr>
  <tr>
   <td>
    5
   </td>
   <td>
    <a href="/wiki/CVS_Health" title="CVS Health">
     CVS Health
    </a>
   </td>
   <td>
    Healthcare
   </td>
   <td style="text-align:center;">
    372,809
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    4.2%
   </td>
   <td style="text-align:center;">
    259,500
   </td>
   <td>
    <a href="/wiki/Woonsocket,_Rhode_Island" title="Woonsocket, Rhode Island">
     Woonsocket, Rhode Island
    </a>
   </td>
  </tr>
  <tr>
   <td>
    6
   </td>
   <td>
    <a href="/wiki/Berkshire_Hathaway" title="Berkshire Hathaway">
     Berkshire Hathaway
    </a>
   </td>
   <td>
    Conglomerate
   </td>
   <td style="text-align:center;">
    371,433
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    1.9%
   </td>
   <td style="text-align:center;">
    392,400
   </td>
   <td>
    <a href="/wiki/Omaha,_Nebraska" title="Omaha, Nebraska">
     Omaha, Nebraska
    </a>
   </td>
  </tr>
  <tr>
   <td>
    7
   </td>
   <td>
    <a class="mw-redirect" href="/wiki/Alphabet_Inc" title="Alphabet Inc">
     Alphabet
    </a>
   </td>
   <td>
    Technology and cloud computing
   </td>
   <td style="text-align:center;">
    350,018
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    13.9%
   </td>
   <td style="text-align:center;">
    183,323
   </td>
   <td>
    <a href="/wiki/Mountain_View,_California" title="Mountain View, California">
     Mountain View, California
    </a>
   </td>
  </tr>
  <tr>
   <td>
    8
   </td>
   <td>
    <a href="/wiki/ExxonMobil" title="ExxonMobil">
     Exxon Mobil
    </a>
   </td>
   <td>
    Petroleum
   </td>
   <td style="text-align:center;">
    349,595
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    1.5%
   </td>
   <td style="text-align:center;">
    60,900
   </td>
   <td>
    <a href="/wiki/Spring,_Texas" title="Spring, Texas">
     Spring, Texas
    </a>
   </td>
  </tr>
  <tr>
   <td>
    9
   </td>
   <td>
    <a href="/wiki/McKesson_Corporation" title="McKesson Corporation">
     McKesson Corporation
    </a>
   </td>
   <td>
    Healthcare
   </td>
   <td style="text-align:center;">
    308,951
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    11.7%
   </td>
   <td style="text-align:center;">
    48,000
   </td>
   <td>
    <a href="/wiki/Irving,_Texas" title="Irving, Texas">
     Irving, Texas
    </a>
   </td>
  </tr>
  <tr>
   <td>
    10
   </td>
   <td>
    <a href="/wiki/Cencora" title="Cencora">
     Cencora
    </a>
   </td>
   <td>
    Pharmacy wholesale
   </td>
   <td style="text-align:center;">
    293,959
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    12.1%
   </td>
   <td style="text-align:center;">
    44,000
   </td>
   <td>
    <a href="/wiki/Conshohocken,_Pennsylvania" title="Conshohocken, Pennsylvania">
     Conshohocken, Pennsylvania
    </a>
   </td>
  </tr>
  <tr>
   <td>
    11
   </td>
   <td>
    <a href="/wiki/JPMorgan_Chase" title="JPMorgan Chase">
     JPMorgan Chase
    </a>
   </td>
   <td>
    Financials
   </td>
   <td style="text-align:center;">
    278,906
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    16.5%
   </td>
   <td style="text-align:center;">
    317,233
   </td>
   <td>
    <a href="/wiki/New_York_City" title="New York City">
     New York City, New York
    </a>
   </td>
  </tr>
  <tr>
   <td>
    12
   </td>
   <td>
    <a href="/wiki/Costco" title="Costco">
     Costco Wholesale
    </a>
   </td>
   <td>
    Retail
   </td>
   <td style="text-align:center;">
    254,453
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    5.0%
   </td>
   <td style="text-align:center;">
    333,000
   </td>
   <td>
    <a href="/wiki/Issaquah,_Washington" title="Issaquah, Washington">
     Issaquah, Washington
    </a>
   </td>
  </tr>
  <tr>
   <td>
    13
   </td>
   <td>
    <a class="mw-redirect" href="/wiki/Cigna" title="Cigna">
     Cigna
    </a>
   </td>
   <td>
    Health insurance
   </td>
   <td style="text-align:center;">
    247,121
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    26.6%
   </td>
   <td style="text-align:center;">
    72,398
   </td>
   <td>
    <a href="/wiki/Bloomfield,_Connecticut" title="Bloomfield, Connecticut">
     Bloomfield, Connecticut
    </a>
   </td>
  </tr>
  <tr>
   <td>
    14
   </td>
   <td>
    <a href="/wiki/Microsoft" title="Microsoft">
     Microsoft
    </a>
   </td>
   <td>
    Technology and cloud computing
   </td>
   <td style="text-align:center;">
    245,122
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    15.7%
   </td>
   <td style="text-align:center;">
    228,000
   </td>
   <td>
    <a href="/wiki/Redmond,_Washington" title="Redmond, Washington">
     Redmond, Washington
    </a>
   </td>
  </tr>
  <tr>
   <td>
    15
   </td>
   <td>
    <a href="/wiki/Cardinal_Health" title="Cardinal Health">
     Cardinal Health
    </a>
   </td>
   <td>
    Healthcare
   </td>
   <td style="text-align:center;">
    226,827
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    10.6%
   </td>
   <td style="text-align:center;">
    48,411
   </td>
   <td>
    <a href="/wiki/Dublin,_Ohio" title="Dublin, Ohio">
     Dublin, Ohio
    </a>
   </td>
  </tr>
  <tr>
   <td>
    16
   </td>
   <td>
    <a href="/wiki/Chevron_Corporation" title="Chevron Corporation">
     Chevron
    </a>
   </td>
   <td>
    Petroleum
   </td>
   <td style="text-align:center;">
    202,792
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    0.9%
   </td>
   <td style="text-align:center;">
    45,298
   </td>
   <td>
    <a class="mw-redirect" href="/wiki/Houston,_Texas" title="Houston, Texas">
     Houston, Texas
    </a>
   </td>
  </tr>
  <tr>
   <td>
    17
   </td>
   <td>
    <a href="/wiki/Bank_of_America" title="Bank of America">
     Bank of America
    </a>
   </td>
   <td>
    Financials
   </td>
   <td style="text-align:center;">
    192,434
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">
      <img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png?utm_source=en.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="11"/>
     </span>
    </span>
    <span data-sort-value="7000300000000000000♠" style="display:none">
    </span>
    11.9%
   </td>
   <td style="text-align:center;">
    213,193
   </td>
   <td>
    <a href="/wiki/Charlotte,_North_Carolina" title="Charlotte, North Carolina">
     Charlotte, North Carolina
    </a>
   </td>
  </tr>
  <tr>
   <td>
    18
   </td>
   <td>
    <a href="/wiki/General_Motors" title="General Motors">
     General Motors
    </a>
   </td>
   <td>
    Automotive
   </td>
   <td style="text-align:center;">
    187,442
   </td>
   <td style="text-align:center;">
    <span typeof="mw:File">
     <span title="Increase">

In [91]:
world_titles = table.find_all('th')
headers = [title.text.strip() for title in world_titles]

print(headers)

['Rank', 'Name', 'Industry', 'Revenue (USD millions)', 'Revenue growth', 'Employees', 'Headquarters']

In [92]:
df = pd.DataFrame(columns=headers)
df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue (USD millions), Revenue growth, Employees, Headquarters]
Index: []

In [95]:
rows = table.find_all('tr')[1:]

for row in rows:
    cols = row.find_all('td')
    if cols:
        clean_row = [col.text.strip() for col in cols]
        df.loc[len(df)] = clean_row
        # print(clean_row)

In [96]:
df.head()

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"680,985",5.1%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"637,959",11.0%,"1,556,000","Seattle, Washington"
2,3,UnitedHealth Group,Healthcare,"400,278",7.7%,"400,000","Minnetonka, Minnesota"
3,4,Apple,Technology,"391,035",2.0%,"164,000","Cupertino, California"
4,5,CVS Health,Healthcare,"372,809",4.2%,"259,500","Woonsocket, Rhode Island"

In [100]:
df.to_csv(r"E:\Learning\Courses\@Youtube\Data Analyst\5. Python\Practice\Companies.csv", index=False)